version: '3.9'

services:


  producer:
    build: ./producer
    ports:
      - 8080:80
    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      EVENT_HUB_FULLY_QUALIFIED_NAMESPACE: ${EVENT_HUB_FULLY_QUALIFIED_NAMESPACE}
      EVENT_HUB_NAME: ${EVENT_HUB_NAME}

  consumer:
    build: 
      context: ./consumer
    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      EVENT_HUB_FULLY_QUALIFIED_NAMESPACE: ${EVENT_HUB_FULLY_QUALIFIED_NAMESPACE}
      EVENT_HUB_NAME: ${EVENT_HUB_NAME}
      EVENT_HUB_CONSUMER_GROUP: alias
      BLOB_STORAGE_ACCOUNT_URL: ${BLOB_STORAGE_ACCOUNT_URL}
      BLOB_CONTAINER_NAME: ${BLOB_CONTAINER_NAME}


  consumerprimary:
    build: 
      context: ./consumer
    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      EVENT_HUB_FULLY_QUALIFIED_NAMESPACE: ${EVENT_HUB_FULLY_QUALIFIED_NAMESPACE_PRIMARY}
      EVENT_HUB_NAME: ${EVENT_HUB_NAME}
      EVENT_HUB_CONSUMER_GROUP: primary
      BLOB_STORAGE_ACCOUNT_URL: ${BLOB_STORAGE_ACCOUNT_URL}
      BLOB_CONTAINER_NAME: ${BLOB_CONTAINER_NAME}

  consumersecondary:
    build: 
      context: ./consumer
    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      EVENT_HUB_FULLY_QUALIFIED_NAMESPACE: ${EVENT_HUB_FULLY_QUALIFIED_NAMESPACE_SECONDARY}
      EVENT_HUB_NAME: ${EVENT_HUB_NAME}
      EVENT_HUB_CONSUMER_GROUP: secondary
      BLOB_STORAGE_ACCOUNT_URL: ${BLOB_STORAGE_ACCOUNT_URL}
      BLOB_CONTAINER_NAME: ${BLOB_CONTAINER_NAME}

  replicator:
    build: 
      context: ./replicator
    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      EVENT_HUB_FULLY_QUALIFIED_NAMESPACE_PRIMARY: ${EVENT_HUB_FULLY_QUALIFIED_NAMESPACE_PRIMARY}
      EVENT_HUB_FULLY_QUALIFIED_NAMESPACE_SECONDARY: ${EVENT_HUB_FULLY_QUALIFIED_NAMESPACE_SECONDARY}
      EVENT_HUB_NAME: ${EVENT_HUB_NAME}
      EVENT_HUB_CONSUMER_GROUP: replicator
      BLOB_STORAGE_ACCOUNT_URL: ${BLOB_STORAGE_ACCOUNT_URL}
      BLOB_CONTAINER_NAME: ${BLOB_CONTAINER_NAME}